### ISSUE TITLE
他掲示板からのデータインポートについて考える

### ISSUE THREAD

**Issue by japankun** [japankun/bbs.jpnkn.com#30]
他掲示板サービスからのインポート機能について何回か聞かれているので
何かいい策がないか考えてみる

### 掲示板管理者のみに許可する
Google Analyticsの所有権認証のような方式で
掲示板デザインで専用タグを埋め込んでもらい、タグの内容が一致する場合のみインポートする。
インポートした内容に関しては掲示板管理者に適切に扱ってもらう必要がある。

**Comment by japankun** [comment]
- インポートに関してはdatのスレッドキーが衝突する可能性があるので注意が必要。
- したらばはdatの書式が違うので扱い方を考える必要がある。

**Comment by japankun** [comment]
- 書き込み数1000超え設定の扱い
- 版の管理(インポート後にまたインポートされたときにどうするか)

**Comment by japankun** [comment]
Internet Archiveのようにスナップショットでデータを取っておいて
書き込みはできない過去ログとして残すといろいろクリアできるかも

**Comment by PYU224** [comment]
初めまして。期待しております。

**Comment by japankun** [comment]
![2020-03-15 01_52_56](https://user-images.githubusercontent.com/7452697/76686592-f4033a80-665f-11ea-98d5-484a8d02d91e.png)

まずは掲示板管理権の認証画面まで

**Comment by PYU224** [comment]
ありがとうございます。これは書き込みの内容のみならず、書き込み者のIPなどの情報も吸い出されるのでしょうか？
実は他の方に掲示板を譲渡するにあたって、内部の書き込みのIPや管理人である私のIPなどの問題がありまして、それらの問題をクリアできる掲示板を探し貴掲示板に目をつけているのですが・・・

Sent from ProtonMail Mobile

日, 3月 15, 2020 at 01:58, Japan-Kun <notifications@github.com> が送信：

**Comment by PYU224** [comment]
Sent from ProtonMail Mobile

日, 3月 15, 2020 at 02:53,

**Comment by japankun** [comment]
現在の仕様では、こちらの管理画面でしたらばの書き込み発信者のIPアドレスの取得はできません。
個別のスレッドや書き込みの管理、削除は、したらば掲示板で行ってもらうことを想定しています。

また既にしたらば掲示板で倉庫送りになっている場合は、したらば掲示板の管理画面でも
発信者のIPアドレス情報が消去されているかと思います。

以下は認証機能が必要な経緯です。

名称をデータインポートとしていますが、完全な移行手段が提供されていないので
現状ではしたらば掲示板の内容をWebブラウザ経由で表示できる
したらば掲示板の専用ビューワのような機能にとどまっています。

これは、仮にしたらば掲示板のサーバーがダウンした場合でも
この専用ビューワ機能を通すことで、今までのしたらば掲示板の内容が表示できるというものです。

ただ、この機能を個々のしたらば掲示板管理者に無断で行うことは
たとえアーカイブやバックアップ機能であっても好ましくないと考えているので
掲示板ごとに認証を設ける必要があるという次第です。

**Comment by japankun** [comment]
画面サンプル

管理画面(連携設定)
![2020-03-17 23_30_05](https://user-images.githubusercontent.com/7452697/76866533-9d883d00-68a7-11ea-96ee-c9b5716c0a01.png)

管理画面(スレッド一覧)
![2020-03-17 23_29_30](https://user-images.githubusercontent.com/7452697/76866522-995c1f80-68a7-11ea-8544-711d8e2047d5.png)

スレッド表示
![2020-03-17 23_31_02](https://user-images.githubusercontent.com/7452697/76866546-a4af4b00-68a7-11ea-9315-6325df14f8f5.png)

**Comment by PYU224** [comment]
ありがとうございます。
言いにくいのですがこちらの都合で移転の話が難航しておりまして、そちらへの移転が無しになるかもしれません。申し訳ございません。

Sent from ProtonMail Mobile

火, 3月 17, 2020 at 23:35, Japan-Kun <notifications@github.com> が送信：

**Comment by japankun** [comment]
ガワはほぼできているのでサーバーの処理を考える

- サーバーアタックになるとまずいので、キュー処理にする
- スレッドの取得間隔を常識的な範囲として15秒 = 5760スレッド/日
- 紳士協定的には1秒に1回程だけど、したらばの調子がよろしくないのでざっくり15倍
- 自動更新はしない
- のんびりしているとしたらばがなくなってるかもしれないのでなるべく早く作る(重要)

**Comment by japankun** [comment]
アーカイブ管理画面
![2020-04-29 18_37_25](https://user-images.githubusercontent.com/7452697/80582230-4ac6a700-8a49-11ea-9443-1a44ccb749b9.png)
![2020-04-29 18_37_42](https://user-images.githubusercontent.com/7452697/80582235-4e5a2e00-8a49-11ea-9b4a-9ca3daaae8a1.png)

外部サービス連携画面
![2020-04-29 18_40_03](https://user-images.githubusercontent.com/7452697/80582240-5023f180-8a49-11ea-991a-112b36d69fc2.png)

**Comment by japankun** [comment]
したらば掲示板との連携機能が利用できるようになりました。
