### ISSUE TITLE
スレッド削除の前にワンクッション置くか取り消せるようにしてほしい

### ISSUE THREAD

**Issue by progre** [japankun/bbs.jpnkn.com#50]
掲示板管理メニュー、レス管理のスレッド削除機能。
「⚠️ 削除ボタンは1クリックで削除されます。」とはいうものの、ログイン直後にうっかり触ってしまうだけで吹っ飛んでしまうのはおっかないです。

 `confirm()` でもいいのでワンクッション置くか、削除を取り消す機能が欲しいです。

レス削除も同様です。レス削除画面は頻繁にアクセスする画面ではないのでスレ削除よりは深刻ではないです。

モチベーション:
- ログイン後の最初のページなので頻繁にアクセスするページである
- 取り消すことができない
- レス=資産と考えると、ワンミスで資産が飛ぶという事

**Comment by japankun** [comment]
いきなりスレッドが消えないように
スレッド管理メニューではダイアログを出して確認するようにしました。

![2021-02-02 22_19_47-thread](https://user-images.githubusercontent.com/7452697/106606429-7876e880-65a5-11eb-8cb9-02dfb020b98a.png)
