### ISSUE TITLE
'@' を含む URL の '@' 以降がリンクとして認識されない

### ISSUE THREAD

**Issue by progre** [japankun/bbs.jpnkn.com#65]
YouTube や mastodon などで、URL に `@` を含むときに正しくリンクとして認識されないようです

例) https://bbs.jpnkn.com/test/read.cgi/progre/1679407614/1
> YouTube https://www.youtube.com/@progre

有効な URL だと思うので、全体をリンクにしてほしいです

**Comment by japankun** [comment]
@と括弧が含まれるURLをリンクとして認識するように修正しました。
